apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: trivy-operator
    repoURL: https://aquasecurity.github.io/helm-charts/
    targetRevision: 0.12.0
    helm:
      releaseName: trivy-operator
      valueFiles:
        - https://raw.githubusercontent.com/stand-sure/trivy-operator/main/value-overrides.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: trivy-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
