apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trust-manager
  namespace: argocd
spec:
  project: default
  source:
    chart: trust-manager
    repoURL: https://charts.jetstack.com
    targetRevision: 0.4.0
    helm:
      releaseName: trust-manager
      values: |
        installCRDs: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
