apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-host1
  namespace: argocd
spec:
  project: default
  source:
    chart: vcluster
    repoURL: https://charts.loft.sh
#    targetRevision: 1.16.1
    helm:
      releaseName: vcluster-host1
      values: |
        vcluster:
          image: rancher/k3s:v1.21.3-k3s1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: host-namespace-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
