apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-operator
  namespace: argocd
spec:
  project: default
  sources:
    - chart: vault-operator
      repoURL: https://kubernetes-charts.banzaicloud.com
      targetRevision: 1.19.0
      helm:
        releaseName: vault-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
