apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: longhorn-system
spec:
  encryptedData:
    auth: AgCkSAHXtUK+naN1jljJBT8Ohh6NIHOevMewkkwInfZKRZ5Kp01kQFy7KXYNlsYazKV3zxIlj6mr7fS0Xkxr+YgNkDQSic5YNe4n3JIsukFP5Mq20uUlWE1IpVKOTMQqlVT1xlPSefaZYxZxUpySrf+E2kGTk9odm2yMmxElZ3gNiovIFBf42/WGXV4ivgg4IrZTDX7HGjyY4f0x0HxrNzB/yDYnv650Mt6pnO/gJNYMb76kAJuw5vavPVFr9ROkktXMYtR4K3YiERpv2VCRpDSAcvilQwtvGAFKm7xsxjFHsj+uG0xBjxQKFLFsCRbj3o551VCtVa/lTiFHwJNM4CnG734+BiSPr/Ppx7HGtN+DjJ4OGlHuIuL4TggaVxZrV21jfGL2scjzZso9cTVcyPsM1OjHWe7vwLPCAFnWT0NhgrHnU6SMzrnue6PmJQlQsRakDdbn6r6MJhWVu6SVJ2R8plMa9wdfSe4YDnb1iEu1prOtplbTEab9DP5S1Hukp4zQqmSnHaC3rmqvjP2sYuFWRzI3D3ALg4f/CcyWt6sl2kvtAwaTO75aRLXiOuodU4ZtbAZatPATYHP/xQ3SyUcVuKOBMQ+0XxLuFZbplLhU4RXNsm0kyw9vSWf1FHY/RwtUjfG150GQrY3hRxxiQeZ4ffyhRiuJchaRoHzvISjBr3V/oZKv8MlVik78aEzeUvF64pDD7I1G6Ik+1GF5a5nhuJ/IN6AgeBa8WVWl5ELcapamIBSzlt025fZg8Cb4RQaa
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: longhorn-system

