apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik.192.168.87.157.nip.io
  namespace: kube-system
spec:
  dnsNames:
    - traefik.192.168.87.157.nip.io
  secretName: traefik.192.168.87.157.nip.io
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer