apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-ingressroute
  namespace: kube-system
spec:
  entryPoints:
  - websecure
  - web
  routes:
  - kind: Rule
    match: Host(`traefik.192.168.87.157.nip.io`)
    middlewares:
    - name: traefik-auth-middleware
    priority: 10
    services:
    - kind: TraefikService
      name: api@internal
  tls:
    secretName: traefik.192.168.87.157.nip.io
